name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup Node.js version 18
      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies for the React app
      - name: Install React app dependencies
        working-directory: ./agency-dashboard
        run: npm install

      # Build the React app
      - name: Build React App
        working-directory: ./agency-dashboard
        run: npm run build

      # Install dependencies for Firebase Functions
      - name: Install Firebase Functions dependencies
        working-directory: ./functions
        run: npm install

      # Build Firebase Functions
      - name: Build Firebase Functions
        working-directory: ./functions
        run: npm run build

      # Deploy to Firebase Hosting and Functions
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting,functions
