name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Build React App
      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Deploy Firebase Hosting
        env:
          FIREBASE_TOKEN: \${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting

      # Build Firebase Functions
      - name: Build Firebase Functions
        working-directory: ./backend-functions
        run: |
          npm install
          npm run lint -- --fix
          npm run build

      - name: Deploy Firebase Functions
        working-directory: ./backend-functions
        env:
          FIREBASE_TOKEN: \${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions
